name: Build and Test Coverage

on:
  pull_request:
    branches:
      - main
      - '**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 (you can change to another version if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Gradle dependencies 
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('marketplace/**/*.gradle*', 'marketplace/**/gradle.properties', 'marketplace/**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x ./marketplace/gradlew

      # Run Gradle build and tests with coverage from within marketplace
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        working-directory: marketplace
        with:
          cache-disabled: true
          generate-job-summary: false

      # Upload the JaCoCo test coverage report 
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-report
          path: marketplace/build/reports/coverage/index.html
