openapi: 3.0.3
info:
  title: Cosmo Cats Intergalactic Marketplace - Product API
  version: "1.0.0"
  description: |
    REST API для керування товарами (Products) в маркетплейсі Cosmo Cats.
    Сучасна космічна тематика: продукти можуть мати антигравітаційний коефіцієнт,
    походження з планети та рейтинг радіаційної безпеки.
  contact:
    name: Cosmo Cats Dev Team
    email: devs@cosmocats.example
servers:
  - url: http://localhost:8080
    description: Локальний сервер (dev)
tags:
  - name: Products
    description: CRUD операції над космічними товарами

paths:
  /api/v1/products:
    get:
      tags: [Products]
      summary: Повернути перелік продуктів (з пагінацією і фільтрацією)
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
        - $ref: '#/components/parameters/sort'
        - name: q
          in: query
          description: Пошуковий рядок (по name, description або originPlanet)
          schema:
            type: string
        - name: minPrice
          in: query
          description: Мінімальна ціна (фільтр)
          schema:
            type: number
            format: double
            minimum: 0
        - name: maxPrice
          in: query
          description: Максимальна ціна (фільтр)
          schema:
            type: number
            format: double
            minimum: 0
      responses:
        '200':
          description: Список продуктів з метаданими пагінації
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductPage'
              examples:
                example-1:
                  summary: Невеликий перелік
                  value:
                    content:
                      - id: 1
                        sku: "CC-AG-0001"
                        name: "Антигравітаційний клубок ниток"
                        description: "Клубок, що піднімається на 0.8G"
                        price: 99.99
                        currency: "USD"
                        originPlanet: "Lunara"
                        antigravityCoefficient: 0.85
                        radiationRating: 1
                        stock: 42
                      - id: 2
                        sku: "CC-SL-0042"
                        name: "Космічне молоко (склянка)"
                        description: "Збагачене кальцієм для міжгалактичних котів"
                        price: 12.5
                        currency: "USD"
                        originPlanet: "Ceres"
                        antigravityCoefficient: 0.00
                        radiationRating: 0
                        stock: 120
                    page: 0
                    size: 10
                    totalElements: 2
                    totalPages: 1
        '400':
          description: Невірні параметри запиту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags: [Products]
      summary: Створити новий продукт
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
            examples:
              new-item:
                value:
                  sku: "CC-AG-9000"
                  name: "Літаючий клубок від Місячної Фірми"
                  description: "Найкращий клубок для антигравітаційних ігор"
                  price: 149.99
                  currency: "USD"
                  originPlanet: "Lunara"
                  antigravityCoefficient: 0.9
                  radiationRating: 1
                  stock: 20
      responses:
        '201':
          description: Створено; повертає створений ресурс
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Помилка валідації вхідних даних
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Конфлікт (наприклад, sku вже існує)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/products/{id}:
    get:
      tags: [Products]
      summary: Отримати продукт за ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Інформація про продукт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Продукт не знайдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags: [Products]
      summary: Повне оновлення продукту (замінити всі поля)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Повертає оновлений продукт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Помилка валідації
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Продукт не знайдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Конфлікт (наприклад, sku міняється на існуючий)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      tags: [Products]
      summary: Часткове оновлення продукту (JSON Merge Patch)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/ProductPartial'
      responses:
        '200':
          description: Повертає оновлений продукт
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '400':
          description: Невірні дані
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Продукт не знайдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags: [Products]
      summary: Видалити продукт
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успішно видалено (No Content)
        '404':
          description: Продукт не знайдено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    page:
      name: page
      in: query
      description: Номер сторінки (0-based)
      schema:
        type: integer
        minimum: 0
        default: 0
    size:
      name: size
      in: query
      description: Розмір сторінки
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    sort:
      name: sort
      in: query
      description: Поле сортування та напрям
      schema:
        type: string

  schemas:
    ProductBase:
      type: object
      properties:
        sku:
          type: string
          description: Унікальний код товару
          example: "CC-AG-0001"
          minLength: 5
          maxLength: 64
          pattern: "^[A-Z0-9\\-]+$"
        name:
          type: string
          minLength: 3
          maxLength: 200
          example: "Антигравітаційний клубок"
        description:
          type: string
          description: Детальний опис товару
          maxLength: 2000
          example: "Клубок, що піднімається на 0.8G — ідеально підходить для космічних котів"
        price:
          type: number
          format: double
          description: Ціна у вказаній валюті
          minimum: 0.0
          example: 99.99
        currency:
          type: string
          description: ISO-код валюти
          pattern: "^[A-Z]{3}$"
          example: "USD"
        originPlanet:
          type: string
          description: Планета чи місце походження
          example: "Lunara"
        antigravityCoefficient:
          type: number
          description: Коефіцієнт антигравітації (0.0 — немає ефекту, 1.0 — повна антигравітація)
          minimum: 0.0
          maximum: 1.0
          example: 0.85
        radiationRating:
          type: integer
          description: Рейтинг радіаційної безпеки (0 — безпечний, 0..5)
          minimum: 0
          maximum: 5
          example: 1
        stock:
          type: integer
          description: Кількість одиниць на складі
          minimum: 0
          example: 42
        weightKg:
          type: number
          description: Вага у кілограмax (опціонально)
          minimum: 0
          example: 0.12
        tags:
          type: array
          items:
            type: string
          example: ["anti-gravity","cat-favorite"]
      required:
        - sku
        - name
        - price
        - currency
        - stock

    ProductCreate:
      allOf:
        - $ref: '#/components/schemas/ProductBase'
      description: Схема для створення продукту. Всі required поля мають бути в запиті.

    ProductUpdate:
      type: object
      description: Повне оновлення продукту (всі поля повинні бути присутні)
      properties:
        id:
          type: integer
          readOnly: true
        <<: {}
      allOf:
        - $ref: '#/components/schemas/ProductBase'

    ProductPartial:
      type: object
      description: Часткове оновлення — містить лише поля, які потрібно змінити
      properties:
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        currency:
          type: string
        originPlanet:
          type: string
        antigravityCoefficient:
          type: number
        radiationRating:
          type: integer
        stock:
          type: integer
        weightKg:
          type: number
        tags:
          type: array
          items:
            type: string

    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          example: 123
        createdAt:
          type: string
          format: date-time
          example: "2025-10-02T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-10-02T12:00:00Z"
        sku:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        currency:
          type: string
        originPlanet:
          type: string
        antigravityCoefficient:
          type: number
        radiationRating:
          type: integer
        stock:
          type: integer
        weightKg:
          type: number
        tags:
          type: array
          items:
            type: string
      required:
        - id
        - sku
        - name
        - price

    ProductPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 10
        totalElements:
          type: integer
          example: 2
        totalPages:
          type: integer
          example: 1

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-10-02T12:00:00Z"
        status:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "Validation failed: price must be >= 0"
        path:
          type: string
          example: "/api/v1/products"
